### ISSUE TITLE
bug: Errors out when emptying search bar

### ISSUE THREAD

**Issue by mrs4ndman** [tomiis4/Hypersonic.nvim#13]
I found these 2 "bugs" when testing some regex search.

If I press <kbd>/</kbd> to start searching, it works. I can keep searching and inputting normal words or Regular expressions and it parses them. The problem comes when I erase the text on the searchbox and go to completely empty again. Step by step:

1. I press <kbd>/</kbd> to start searching (I have Noice on for UI stuff):
![image](https://github.com/tomiis4/hypersonic.nvim/assets/121260905/c77d7489-7af2-497d-b5b2-721d6d1a801c)
2. I type what I want to search:
![image](https://github.com/tomiis4/hypersonic.nvim/assets/121260905/22b32e2f-00db-4133-a7bd-5c768bc431c8)

3. But when I erase to change my current search, this happens:
![image](https://github.com/tomiis4/hypersonic.nvim/assets/121260905/59be18c8-dfac-45a7-b0fd-0c91ceb4a789)

It does allow me to write again my search prompt, but it errors out. It is not a breaking bug, but it's inconvenient to get this error when I change my mind about the search I am doing.

I also did notice that my Neovim instance (NVIM v0.10.0-dev-642+gc44d819ae) freezes when the plugin is enabled and I try to search for `(`, `[`, `{`, and their closing brackets. If that is a WIP feature, do let me know

- The `hypersonic.lua` in my Neovim config, for context:
```Lua
return {
  "tomiis4/hypersonic.nvim",
  event = "CmdlineEnter",
  cmd = "Hypersonic",
  config = function()
    require("hypersonic").setup({
      -- config
    })
  end,
}
```

**Comment by tomiis4** [comment]
Thank you so much for spotting this. I'll fix this soon.

**Comment by tomiis4** [comment]
Cmdline searching error should be fixed in newest commit.
I made new issue for searching for `()` #14 because it will maybe take some time.
