### ISSUE TITLE
images in README are broken

### ISSUE THREAD

**Issue by iguanacucumber** [tomiis4/Hypersonic.nvim#18]
![image](https://github.com/user-attachments/assets/f3123ebf-f092-4674-aeb7-0aa8f856415a)
Discord links only work temporarly
![image](https://github.com/user-attachments/assets/181406c4-c600-4f2c-8a75-3d99307648f9)

**Comment by iguanacucumber** [comment]
and this is the same for BufEx.nvim and your dotfiles ( & buffertabs images will soon stop working )

**Comment by tomiis4** [comment]
oh, I didn't knew about that, Thank you so much <3

**Comment by iguanacucumber** [comment]
closing as this is now fixed :D
