### ISSUE TITLE
Is it possible to change the wrapping quotes?

### ISSUE THREAD

**Issue by nyngwang** [tomiis4/Hypersonic.nvim#5]
## Problem

When there are some double quotes in the regex pattern being interpreted, the result is a bit confusing:

<img src="https://github.com/tomiis4/hypersonic.nvim/assets/24765272/d59d21c0-5b23-420e-9b44-4ada7568cf81" width="600">

## Proposed Solution

It will be great if we can customize the wrapping characters for every sub-pattern.

Personally, I will be happy if I can use a single space as the wrapping characters, i.e. I would prefer to use an invisible wrapping character.

**Comment by tomiis4** [comment]
Of course, I'll add that to the config, also please note that this plugin does not support tokens in the moment for LUA so it's not giving _correct_ explanation.

**Comment by nyngwang** [comment]
Great

> also please note that [...]

Thanks :) You're careful-minded for that part. It's OK for me to be not precise at the beginning.

**Comment by tomiis4** [comment]
Fixed in #6, in your config just set `wrapping` to whatever you like 😁
