### ISSUE TITLE
Got an error with the cmdline `/` feature: Hypersonic.nvim/lua/hypersonic/utils.lua:46: bad argument #1 to 'sub' (string expected, got table)

### ISSUE THREAD

**Issue by nyngwang** [tomiis4/Hypersonic.nvim#8]
## To reproduce

1. first call the cmdline feature `:Hypersonic gr[ae]y`. This should work without an error.
2. press `/` and type `gr[ae]y` character by character. Should get the error after pressing `[`.

## Error message

```
CmdlineChanged Autocommands for "*": Vim(append):Error executing lua callback: ...share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/utils.lua:46: bad argument #1 to 'sub' (string expected, got table)
stack traceback:
	[C]: in function 'sub'
	...share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/utils.lua:46: in function 'is_escape_char'
	...share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/merge.lua:219: in function 'Merge'
	.../share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/init.lua:56: in function 'get_informations'
	.../share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/init.lua:203: in function 'explain'
	.../share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/init.lua:182: in function <.../share/nvim/lazy/Hypersonic.nvim/lua/hypersonic/init.lua:176>
```

**Comment by tomiis4** [comment]
Thank you and I'm very sorry for those bugs 😅
I haven't noticed this one when I was testing this one.

**Comment by nyngwang** [comment]
> I haven't noticed this one when I was testing this one.

It's OK :) I just realized that without step 1. there is no error too. So it's a little tricky to reproduce(?)

**Comment by tomiis4** [comment]
This error is connected with *Works only for correctly written regex*, you get this message each time you write error. (You can still see it in `:messages`). 
By end of tomorrow it should be fixed.
